title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Jennifer Panzo: https://github.com/jennpanzo

layout: minimal
title: Production Efficiency Dashboard
nav_enabled: false
search_enabled: false
