title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

# aux_links:
#   Jennifer Panzo: https://github.com/jennpanzo

layout: minimal
title: Production Efficiency Dashboard
nav_enabled: false
search_enabled: false

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2025 Jennifer Panzo. Explore more of my work <a href="http://jenn.ph/">here</a>. '
